### ISSUE TITLE
Dialog Framework: issue when embedded in iFrame

### ISSUE THREAD

**Issue by naveenkumarg-oss** [primefaces/primefaces#1403]
We are having issue using Dialog Framework when used within iFrame. I have provided code below to reproduce. 

This always worked in 5.2 and 5.3. I am seeing problem with RC2 as well as RC4-snapshot.

On the Console I see JS error:
TypeError: this.createWidget is not a function (core.js...NAPSHOT (line 287, col 13))
this.createWidget(widgetName, widgetVar, cfg);

![deleteme](https://cloud.githubusercontent.com/assets/12218059/15147799/2aa91b50-16e0-11e6-9576-5e9da6325722.png)

```
<html>
<head>
<script language="JavaScript">          
    function windowWidth() {
        if (window.innerWidth) 
            return parseInt(window.innerWidth) - 18;
        if (document.documentElement && document.documentElement.clientWidth) 
            return parseInt(document.documentElement.clientWidth);
        if (document.body && document.body.clientWidth) return parseInt(document.body.clientWidth);
            return 0;
    }

    function windowHeight() {
        if (window.innerHeight) 
            return parseInt(window.innerHeight) - 18;
        if (document.documentElement && document.documentElement.clientHeight) 
            return parseInt(document.documentElement.clientHeight);
        if (document.body && document.body.clientHeight) 
            return parseInt(document.body.clientHeight);
        return 0;
    }   

    function init() 
    {
        resizeServiceArea();
    }   

    function resizeServiceArea()
    {
        document.getElementById("serviceArea").style.height = (windowHeight()-100) +"px";
        var width = windowWidth();
        width<810?width=810:"";
        document.getElementById("serviceArea").style.width = width +"px";
    }

    window.onload = init;
    //window.onresize = resizeServiceArea;
</script>
</head>
<body id="body">
        <h1>Welcome</h1>
    <iframe src="http://localhost:8080/showcase/ui/df/basic.xhtml" name="serviceArea" id="serviceArea" scrolling="yes" frameborder="1"></iframe>
</body>
</html>
```

**Comment by Marijaaa** [comment]
I've also noticed this. When used inside iFrame, dialog appends to parent's body and thus becomes unresponsive. Is there any workaround for this?

**Comment by tandraschko** [comment]
Thanks for the PR!
