### ISSUE TITLE
DatePicker: Uncaught TypeError in primefaces 8

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#8133]
### Environment

PrimeFaces version: primefaces 8 + primefaces elite 8.0.13 and 8.0.14
JSF: Mojarra-2.3

### Expected behavior

No javascript error must occur. Datepicker must display.

### Actual behavior

The following javascript error is generated:

Uncaught TypeError: this.viewDate.getMonth is not a function
    at K.<computed>.<computed>.renderDateView (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.renderDateView (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>.renderPanelElements (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.renderPanelElements (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>.updateViewDate (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.updateViewDate (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>.hideOverlay (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.hideOverlay (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)
    at K.<computed>.<computed>.onInputKeyDown (datepicker.js.xhtml?ln=primefaces&v=8.0:1)
    at K.<computed>.<computed>.onInputKeyDown (jquery-plugins.js.xhtml?ln=primefaces&v=8.0:14)

In some inputs (8.0.13) after this error the datepicker popup does not display (a page reload is needed to fix state).

### Steps to reproduce

- url: https://www.primefaces.org/showcase-v8/ui/csv/basic.xhtml
- select field: Date (java.util.Date; PF DatePicker)
- type: aaaa 
- press tab
- open browser javascript console (F12 or Ctrl+Shift+J in Chrome)

**Comment by tandraschko** [comment]
works fine in 11.0, so i will close it

@mertsincan would you like to fix it elite?

**Comment by DazzlingBob** [comment]
Is there a way to manualy include a newer version of the datepicker.js in primefaces 8?

**Comment by tandraschko** [comment]
you can the extract the file from a newer JAR and replace it in your older JAR
or place the file in your project and include it in h:head last facet

**Comment by DazzlingBob** [comment]
@mertsincan please fix this issue in elite 8.0.15?
 
 The original issue is: https://github.com/primefaces/primefaces/issues/5683
 The code change is: https://github.com/primefaces/primefaces/pull/5687/commits/236cc2e78a091fbe48a448648fbb5aaecea2ba27
 
 It has been an issue for more than 1.5 years.

**Comment by melloware** [comment]
@DazzlingBob just use this MonkeyPatch in your JS file that loads after PF.

```javascript
$.prime.datePicker.prototype.hideOverlay = function() {
    if (this.panel) {
        if (this.options.onBeforeHide) {
            this.options.onBeforeHide.call(this);
        }

        this.unbindDocumentClickListener();
        this.datepickerClick = false;

        this.panel.hide();

        var viewDate = this.options.viewDate && !this.value ?
            this.parseValue(this.options.viewDate) :
            ((((this.isMultipleSelection() || this.isRangeSelection()) && this.value instanceof Array) ? this.value[0] : this.value) || this.parseValue(new Date()));

        if (viewDate instanceof Date) {
            this.updateViewDate(null, viewDate);
        }
    }
};
```

**Comment by DazzlingBob** [comment]
With the MonkeyPatch the DatePicker issue is fixed.

@melloware Thanks for the MonkeyPatch, made my day!

**Comment by melloware** [comment]
Happy to help!
