### ISSUE TITLE
SelectOneMenu dropdown does not popup and throws jquery error "r.getClientRects is not a function"

### ISSUE THREAD

**Issue by ravikrsk** [primefaces/primefaces#4695]
Tried upgrading PrimeFaces form version 6.1.4  to 6.2.13 (and above), (in Spring-4.3.8.RELEASE + JSF2.2.18 application), and all the SelectOneMenu and autoComplete components dropdowns does not popup, on click, and throws jquery error "r.getClientRects is not a function".

## 1) Environment
- Works fine on PrimeFaces version 6.1.4 
- Does not work with PrimeFaces version:  6.2.13 and above. Even tried using PrimeFaces version 7.0 and had the same issue. 
- Same issue when tried with upgrading JSF from 2.2 to 2.3( using mojarra23 - org.glassfish.javax.faces-2.3.8)
- Affected browsers:  Chrome, IE 11, Mozilla Firefox

## 2) Expected behavior
After Upgrading PrimeFaces version from 6.1.4  to  6.2.x or 7.0, SelectOneMenu dropdown, on click, should popup.

## 3) Actual behavior
SelectOneMenu dropdown, on click, does not popup and throws 
jquery.js.jsf?ln=primefaces&v=7.0:2 Uncaught TypeError: r.getClientRects is not a function
    at w.fn.init.offset (jquery.js.jsf?ln=primefaces&v=7.0:2)
    at Object.getWithinInfo (jquery.ui.position.j…?ln=contextMenu:123)
    at w.fn.init.$.fn.position (jquery.ui.position.j…?ln=contextMenu:145)
    at c.alignPanel (components.js.jsf?ln=primefaces&v=7.0:19)
    at c._show (components.js.jsf?ln=primefaces&v=7.0:19)
    at callHandleMethod (components.js.jsf?ln=primefaces&v=7.0:19)
    at c.show (components.js.jsf?ln=primefaces&v=7.0:19)
    at HTMLLabelElement.<anonymous> (components.js.jsf?ln=primefaces&v=7.0:19)
    at HTMLLabelElement.dispatch (jquery.js.jsf?ln=primefaces&v=7.0:2)
    at HTMLLabelElement.y.handle (jquery.js.jsf?ln=primefaces&v=7.0:2)
 

## 5) Sample XHTML

      <p:selectOneMenu id="console" value="Xbox One" style="width:125px">
            <f:selectItem itemLabel="Select One" itemValue="" />
            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
            <f:selectItem itemLabel="PS4" itemValue="PS4" />
            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
        </p:selectOneMenu>                                    

## 6) Sample bean

No need of any bean, static values in XHTML, as give above, is good enough to reproduce the actual behavior in the application.

**Comment by tandraschko** [comment]
works fine for me - testet with showcase and 7.0.
If you can provide a forked primefaces-test project to replicate the issue, i can have a look at it again.

**Comment by melloware** [comment]
Make sure you don't have two versions of Primefaces classloaded as well.

**Comment by ravikrsk** [comment]
The issue is with our local "jquery.contextMenu.js" not in sync with the latest Primefaces JQuery version.  Primefaces SelectOneMenu works fine after I commented out "jquery.contextMenu.js" 

Appreciate your time, on this.

**Comment by melloware** [comment]
@ravikrsk no problem. Feel free to close the ticket.

**Comment by ravikrsk** [comment]
closing the issue.
