### ISSUE TITLE
commandLink in repeat does not work in PrimeFaces 8.0

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#5700]
## 1) Environment
PrimeFaces version: PrimeFaces-8.0
Application server: Jetty 9.4.27 + version: Mojarra-2.2.20

## 2) Expected behavior
When a button link is pressed the text "Button x pressed" appears.
In PF7, this was no problem at all.

## 3) Actual behavior
Crash:
com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NoSuchMethodError: javax.faces.event.FacesEvent.getFacesContext()Ljavax/faces/context/FacesContext;
        at org.primefaces.component.repeat.UIRepeat.broadcast(UIRepeat.java:916)

## 4) Steps to reproduce
Click a button link! 

## 5) Sample XHTML /Sample bean
See attached project.
[primefaces-test-repeat.zip](https://github.com/primefaces/primefaces/files/4340319/primefaces-test-repeat.zip)

**Comment by tandraschko** [comment]
Duplicate of: https://github.com/primefaces/primefaces/issues/5661

**Comment by DazzlingBob** [comment]
Did not see it was already reported. Just found out when upgrading to 8.0.
Workaround found, use <ui:repeat>
