### ISSUE TITLE
p:graphicImage gives NoSuchMethodError after migrating to 6

### ISSUE THREAD

**Issue by zeeshanrb** [primefaces/primefaces#1859]
My Application was able to render dynamic jpeg images with Primefaces 5.3. Once i migrated to 6.0, my dynamic p:graphicImages are giving NoSuchMethodError related to EL. 
## 1) Environment
- PrimeFaces version: 6
- Does it work on the newest PrimeFaces version? NO
- Application server + version: Weblogic11g 
- Affected browsers: IE,Chrome,Firefox
## 2) Expected behavior

Should support EL 2.1, as primefaces is well know for backward compatibility
...
## 3) Actual behavior

Gives below exception while rendering images.

> PrimeExceptionHandler logException
> javax.el.ValueExpression.getValueReference(Ljavax/el/ELContext;)Ljavax/el/ValueReference; java.lang.NoSuchMethodError: javax.el.ValueExpression.getValueReference(Ljavax/el/ELContext;)Ljavax/el/ValueReference; at org.primefaces.el.ValueExpressionAnalyzer.toValueReference(ValueExpressionAnalyzer.java:91) at org.primefaces.el.ValueExpressionAnalyzer.getExpression(ValueExpressionAnalyzer.java:44) at org.primefaces.util.DynamicResourceBuilder.build(DynamicResourceBuilder.java:58) at org.primefaces.component.graphicimage.GraphicImageRenderer.getImageSrc(GraphicImageRenderer.java:75) at org.primefaces.component.graphicimage.GraphicImageRenderer.encodeEnd(GraphicImageRenderer.java:41) at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:884) at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1681) at javax.faces.render.Renderer.encodeChildren(Renderer.java:168) at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:854) at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:85) at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)

..
## 4) Steps to reproduce

the above code is similar to the one in showcase
.. 
## 5) Sample XHTML

`<p:graphicImage value="#{filebean.image}" />`

..
## 6) Sample bean

`@ManagedBean(name="filebean")
@RequestScoped

public class FileBean {

private StreamedContent image;

public StreamedContent getImage() {
    try {
        File file = new File("C:/LEAVEMODULEFOLDER/569_q318d09lou9mafbqsdgsqph1ar_cbblogopng.jpg");

```
    System.out.println(""+file.canRead());
    image = new DefaultStreamedContent(new FileInputStream(file), "image/jpeg");
```

} catch (Exception e) {
    log.error("Error in ::" + e);
    log.error(Utility.getStackTrace(e));
}

return this.image;
}
}
`
..

Also refer below
http://forum.primefaces.org/viewtopic.php?f=3&t=47584

**Comment by tandraschko** [comment]
javax.el.ValueReference was introduced in EL 2.2 and should not be available in your environment?
So i can't fix in it all cases....

**Comment by tandraschko** [comment]
I fixed in the normal cases, everything else requires EL 2.2. Please try.

**Comment by zeeshanrb** [comment]
So does this mean that EL2.0 is not supported entirely by primefaces 6 ?

**Comment by tandraschko** [comment]
Partially. You can't use p:graphicImage in composite components when you pass the expression when you use < EL 2.2.
