### ISSUE TITLE
UploadedFile: Migration documention required

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#10496]
### Describe the bug

My application does not compile with the current 14.0.0-SNAPSHOT. I have a class MyUploadedFile which implements UploadedFile. There must be a breaking change w.r.t. to UploadedFile since I am getting this error:

`MyUploadedFile is not abstract and does not override abstract method getWebkitRelativePath() in org.primefaces.model.file.UploadedFile`

I just quickly added the attribute and method below (as it was done in the class AbstractUploadedFile) without knowing about the implications of this attribute which in my case is simply unused at the moment:

```
    private String webkitRelativePath;

    @Override
    public String getWebkitRelativePath() {
        return webkitRelativePath;
    }
```

By the way, please note that there is an inconsistency in the naming (ebkit -> 10 cases vs. ebKit -> 11 cases). Would be good if this could be fixed, too. Looking at the code, I assume that you need to consistently use "ebkit".

However, even after adding this required method to my class (which helps to compile and deploy the application), the corresponding file upload button does not popup anymore. So there must be something more to be migrated, probably related to this new attribute! Since I am getting no (error/log) messages, I have no idea where to search for the problem. Appreciate any hints. Please document how to migrate the file upload functionality. 

Many thanks for all your support in advance.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-SNAPSHOT

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by melloware** [comment]
I will fix this thanks for reporting.
