### ISSUE TITLE
FileUpload: uploadedFile.write(path) throws exception "org.owasp.esapi.ESAPI not found"

### ISSUE THREAD

**Issue by teatwig** [primefaces/primefaces#4752]
## 1) Environment
- PrimeFaces version: 7.0
- Application server + version: n.a. (tested with Tomcat 8.5.27, PF Test Jetty 9.4.15.v20190215)
- Affected browsers: n.a. (tested with Firefox 66, Chrome 74)

## 2) Expected behavior
Files uploaded with the `UploadedFile#write(String)` method will be written to the specified path.
This was working fine with PrimeFaces 6.2.

## 3) Actual behavior
An exception is thrown: `java.lang.NoClassDefFoundError: org/owasp/esapi/ESAPI`
<details><summary>Full stacktrace</summary>
<pre>
WARNING: /test.xhtml @18,78 fileUploadListener="#{fileBean.handleFileUpload}": java.lang.NoClassDefFoundError: org/owasp/esapi/ESAPI
javax.el.ELException: /test.xhtml @18,78 fileUploadListener="#{fileBean.handleFileUpload}": java.lang.NoClassDefFoundError: org/owasp/esapi/ESAPI
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:111)
	at org.primefaces.component.fileupload.FileUpload.broadcast(FileUpload.java:63)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:755)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:931)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/owasp/esapi/ESAPI
	at org.primefaces.shaded.owasp.esapi.errors.EnterpriseSecurityException.<init>(EnterpriseSecurityException.java:43)
	at org.primefaces.shaded.owasp.esapi.errors.ValidationException.<init>(ValidationException.java:48)
	at org.primefaces.util.FileUploadUtils.getValidFilePath(FileUploadUtils.java:107)
	at org.primefaces.model.NativeUploadedFile.write(NativeUploadedFile.java:131)
	at org.primefaces.test.FileBean.handleFileUpload(FileBean.java:20)
	at org.primefaces.test.FileBean$$OwbNormalScopeProxy0.handleFileUpload(org/primefaces/test/FileBean.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at org.apache.webbeans.el22.WrappedMethodExpression.invoke(WrappedMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	... 42 more
Caused by: java.lang.ClassNotFoundException: org.owasp.esapi.ESAPI
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 56 more
</pre>
</details>

## 4) Cause
When classes from org.owasp.esapi:esapi are shaded into the final PrimeFaces JAR the compiled class `org.primefaces.shaded.owasp.esapi.errors.EnterpriseSecurityException` still has an import for `org.owasp.esapi.ESAPI` (instead of a non-existant `org.primefaces.shaded.owasp.esapi.ESAPI`) because this class isn't added to the final JAR. 
Adding ESAPI as an additional dependency results in a new exception, because PrimeFaces expects the shaded logger and not the original one:
`java.lang.NoSuchMethodError: org.owasp.esapi.ESAPI.getLogger(Ljava/lang/String;)Lorg/primefaces/shaded/owasp/esapi/Logger;`

## 5) Additional thoughts
If all necessary classes were included we'd get a ValidationException from FileUploadUtils (https://github.com/primefaces/primefaces/blob/c37b93c11b81a390789e41f37d3b8feb73ff71f3/src/main/java/org/primefaces/util/FileUploadUtils.java#L106-L108) because the `getValidFilePath(...)` method checks if a file exists, meaning we can't write new uploaded files with the `write` method. The `getValidFilePath(...)` is used in both implementations of `UploadedFile`.
Our current workaroud is to get an InputStream from the UploadedFile instead and write that to disk manually.

## 6) Steps to reproduce
See test repository: https://github.com/teatwig/primefaces-test-fileupload

**Comment by tandraschko** [comment]
@cnsgithub / @melloware interessted to investigate?

**Comment by melloware** [comment]
I can investigate.

**Comment by melloware** [comment]
So I updated to keep adding one class at a time.

```xml
                            <includes>
                                <include>org.owasp.esapi.ESAPI</include>
                                <include>org.owasp.esapi.SafeFile</include>
                                <include>org.owasp.esapi.Logger</include>
                                <include>org.owasp.esapi.errors.ValidationException</include>
                                <include>org.owasp.esapi.errors.EnterpriseSecurityException</include>
                                <include>org.owasp.esapi.errors.ConfigurationException</include>
                                <include>org.owasp.esapi.reference.DefaultSecurityConfiguration</include>
                                <include>org.owasp.esapi.util.ObjFactory</include>
                            </includes>
```

However even though we are including DefaultSecurityConfiguration it is still blowing up with...

```
org.primefaces.shaded.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException: org.primefaces.shaded.owasp.esapi.reference.DefaultSecurityConfiguration SecurityConfiguration class (org.primefaces.shaded.owasp.esapi.reference.DefaultSecurityConfiguration) must be in class path.
        at org.primefaces.shaded.owasp.esapi.util.ObjFactory.make(ObjFactory.java:108)
        at org.primefaces.shaded.owasp.esapi.ESAPI.securityConfiguration(ESAPI.java:184)
        at org.primefaces.shaded.owasp.esapi.ESAPI.logFactory(ESAPI.java:137)
        at org.primefaces.shaded.owasp.esapi.ESAPI.getLogger(ESAPI.java:154)
        at org.primefaces.shaded.owasp.esapi.errors.EnterpriseSecurityException.<init>(EnterpriseSecurityException.java:43)
        at org.primefaces.shaded.owasp.esapi.errors.ValidationException.<init>(ValidationException.java:48)
        at org.primefaces.util.FileUploadUtils.getValidFilePath(FileUploadUtils.java:107)
```

**Comment by tandraschko** [comment]
the problem is in ESAPI.java:
`private static String securityConfigurationImplName = System.getProperty("org.owasp.esapi.SecurityConfiguration", "org.owasp.esapi.reference.DefaultSecurityConfiguration");`

**Comment by tandraschko** [comment]
hmmm, i think we have to remove the shading... it's not built for shading internally. Just look in DefaultSecurityConfiguration.

it even has a dependency to fileupload somehow.... 

`SCHWERWIEGEND: java.lang.NoClassDefFoundError: org/apache/commons/fileupload/FileItemFactory
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.primefaces.shaded.owasp.esapi.util.ObjFactory.make(ObjFactory.java:74)
        at org.primefaces.shaded.owasp.esapi.ESAPI.httpUtilities(ESAPI.java:121)
        at org.primefaces.shaded.owasp.esapi.ESAPI.currentRequest(ESAPI.java:70)
        at org.primefaces.shaded.owasp.esapi.reference.JavaLogFactory$JavaLogger.log(JavaLogFactory.java:308)
        at org.primefaces.shaded.owasp.esapi.reference.JavaLogFactory$JavaLogger.warning(JavaLogFactory.java:235)
        at org.primefaces.shaded.owasp.esapi.reference.DefaultIntrusionDetector.addException(DefaultIntrusionDetector.java:65
        at org.primefaces.shaded.owasp.esapi.errors.EnterpriseSecurityException.<init>(EnterpriseSecurityException.java:101)
        at org.primefaces.shaded.owasp.esapi.errors.ValidationException.<init>(ValidationException.java:48)
        at org.primefaces.util.FileUploadUtils.getValidFilePath(FileUploadUtils.java:128)`

**Comment by tandraschko** [comment]
maybe we can also overwrite the ValidationException
not sure.
@cnsgithub  any idea?

**Comment by melloware** [comment]
@tandraschko I wonder if this is worth us just copying those 3 classes into PF and cutting out any unnecessary code.  I know we have tried to avoid that with shading but this one is just too messy I think its worth copying a few classes.

**Comment by tandraschko** [comment]
yep probably better; +1

**Comment by tandraschko** [comment]
@mertsincan good fix for ELITE

**Comment by melloware** [comment]
OK so now with my fix to move SafeFile into our code its throwing a proper exception.
```
Trying to upload file to: C:\Temp\pf-4752/uploaded/2019-01-bill-att.pdf
org.primefaces.shaded.owasp.ValidationException: Invalid directory Invalid directory, "C:\Temp\pf-4752\uploaded\2019-01-bill-att.pdf" does not exist.
```

Basically it is correctly saying that the directory does not exist.  So the code is being called to validate before it writes the part out and the Part write automatically creates the directory if it doesn't exist.

```java
public void write(String filePath) throws Exception {
        String validFilePath = FileUploadUtils.getValidFilePath(filePath);

        if (parts != null) {
            for (int i = 0; i < parts.size(); i++) {
                Part p = parts.get(i);
                p.write(validFilePath);
            }
        }
        else {
            part.write(validFilePath);
        }
    }
```
Still investigating.

**Comment by melloware** [comment]
Got past the first bug now onto the second one where this code I don't think will ever work on Windows which is what I am testing on.

```java
if (!file.getCanonicalPath().equals(filePath)) {
                throw new ValidationException("Invalid directory", "Invalid directory name does not match the canonical path");
            }
```

Throws this error.

```
Trying to upload file to: C:\Temp\pf-4752/uploaded/2019-01-bill-att.pdf
org.primefaces.shaded.owasp.ValidationException: Invalid directory Invalid directory name does not match the canonical path
        at org.primefaces.util.FileUploadUtils.getValidFilePath(FileUploadUtils.java:125)
```

**Canonical Path:** C:\Temp\pf-4752\uploaded\2019-01-bill-att.pdf
**Path:** C:\Temp\pf-4752/uploaded/2019-01-bill-att.pdf

So I believe this check must be removed because with the slashes these two paths will never be equal in Windows.

**Comment by melloware** [comment]
OK so the difference between Commons File Upload and the Native Uploader. The Native Uploader does not allow you to specific a directory so I am getting this error.

```
Trying to upload file to: C:\Temp\pf-4752/uploaded/2019-01-bill-att.pdf
java.io.FileNotFoundException: C:\Temp\pf-4752\target\tmp\C:\Temp\pf-4752\uploaded\2019-01-bill-att.pdf (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:336)
        at org.primefaces.model.NativeUploadedFile.write(NativeUploadedFile.java:140)
```
That is is according to the Part.write says this...

**fileName** _the name of the file to which the stream will bewritten. The file is created relative to the location asspecified in the MultipartConfig_

So Jetty is setting the MutliPartConfig to "C:\Temp\pf-4752\target\tmp" so you can only pass Part a file name NOT a full path to "'uploaded".

**Comment by melloware** [comment]
Patch submitted.

**Comment by jasonex7** [comment]
> OK so the difference between Commons File Upload and the Native Uploader. The Native Uploader does not allow you to specific a directory so I am getting this error.
> 
> ```
> Trying to upload file to: C:\Temp\pf-4752/uploaded/2019-01-bill-att.pdf
> java.io.FileNotFoundException: C:\Temp\pf-4752\target\tmp\C:\Temp\pf-4752\uploaded\2019-01-bill-att.pdf (The filename, directory name, or volume label syntax is incorrect)
>         at java.io.FileOutputStream.open0(Native Method)
>         at java.io.FileOutputStream.open(FileOutputStream.java:270)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
>         at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:336)
>         at org.primefaces.model.NativeUploadedFile.write(NativeUploadedFile.java:140)
> ```
> 
> That is is according to the Part.write says this...
> 
> **fileName** _the name of the file to which the stream will bewritten. The file is created relative to the location asspecified in the MultipartConfig_
> 
> So Jetty is setting the MutliPartConfig to "C:\Temp\pf-4752\target\tmp" so you can only pass Part a file name NOT a full path to "'uploaded".

@melloware is this still true? Because the [javadoc of Part.write method in Servlet 4.0 spec](https://javadoc.io/static/javax.servlet/javax.servlet-api/4.0.0/javax/servlet/http/Part.html#write-java.lang.String-) says:

*fileName* - The location into which the uploaded part should be stored. The value may be a file name **or a path**. The actual location of the file in the filesystem is relative to MultipartConfigElement.getLocation(). Absolute paths are used as provided and are relative to getLocation(). Note: that this is a system dependent string and URI notation may not be acceptable on all systems. For portability, this string should be generated with the File or Path APIs.

So Part.write should support a path or an absolute path. Wildfly jakartaee 8 implementation supports what the specs says.

**Comment by melloware** [comment]
Interesting.   I would open a new ticket if you feel this is something that needs to be addressed?

**Comment by jasonex7** [comment]
OK or maybe should be this one. I'm preparing a pull request to support path in write method of `NativeUploadedFile`.

**Comment by melloware** [comment]
Sure thing!
