### ISSUE TITLE
Primefaces Mobile, error getting dynamic data

### ISSUE THREAD

**Issue by srbala** [primefaces/primefaces#413]
Primefaces version 5.3 snapshot

Primefaces mobile dynamic data not working, with 5.3-SNAPSHOT

http://localhost:8080/showcase/mobile/dataList.xhtml advanced list second page
http://localhost:8080/showcase/mobile/accordion.xhtml Dynamic, click on God Father III link

They are working in 5.2 release, PrimeFaces public demo 5.2.5-snapshot is working but fails on 5.3-SNAPSHOT.

**Comment by cagataycivici** [comment]
@tandraschko activeElement.getSelection is not a function error is given, do you have any feedback?

**Comment by tandraschko** [comment]
Weird....
                        var activeElement = $(document.activeElement);
                        var activeElementId = activeElement.attr('id');
                        var activeElementSelection = activeElement.getSelection();

maybe the jquery-plugins.js is missing?

**Comment by cagataycivici** [comment]
What is the dependency to jquery-plugins?

**Comment by cagataycivici** [comment]
You can replicate it by running showcase with 5.3

**Comment by tandraschko** [comment]
the plugin to get/set the current selection of an inputtext - don't know the name but we already used it in textarea or autocomplete

**Comment by cagataycivici** [comment]
But this was working with 5.2, that is weird. I'll tell @mertsincan to dig this. Thanks.

**Comment by tandraschko** [comment]
i added the functionality to remember the caret position after ajax updates, therefor it's a new feature.
but i also added the @ResourceDepedency on the AjaxBebehavior.

**Comment by mertsincan** [comment]
Please try with 5.3.5+, 5.2.18+ and 6.0
