### ISSUE TITLE
Calendar: seems broken in PF 12

### ISSUE THREAD

**Issue by cocorossello** [primefaces/primefaces#9173]
### Describe the bug

<p:calendar/> does not work in PF 12.0.0.RCx, it was working in 11.

Although it is deprecated, I guess it still should work.

Simple reproducer:

`<h:body>
    <h:form id="frmTest">
        <p:calendar/>
    </h:form>
</h:body>`

### Reproducer

https://github.com/cocorossello/primefaces-test/

### Expected behavior

calendar should work as in 11.0.0

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC-3

### JSF implementation

MyFaces

### JSF version

2.3-NEXT-M6

### Java version

18.0.2

**Comment by cocorossello** [comment]
Throws js error:
`Uncaught TypeError: a.getJQ(...).scrollParent is not a function`

I can also see this error in my project:
`Uncaught TypeError: u._base_updateDatepicker is not a function`

I guess it seems related to https://github.com/primefaces/primefaces/commit/174bb7807423c490fccc92574f20a114d5e31045

**Comment by melloware** [comment]
I will take a look.

**Comment by RamiBECHEIKH** [comment]
I have the same exception when open calendar after second failed validation of another component

Uncaught TypeError: u._base_updateDatepicker is not a function
    _updateDatepicker http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:177
    setTimeout handler*$.datepicker._updateDatepicker http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:177
    _showDatepicker http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:45
    dispatch http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    handle http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    add http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    Ee http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    each http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    each http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    Ee http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    on http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    skinInput http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:12
    init http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:188
    Class.extend/f[g]< http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:94
    d http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:94
    createWidget http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:19
    cw http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:19
    <anonymous> http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:1
    b http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    He http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    append http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    html http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    B http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    html http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    handle http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:23
    doUpdate http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:65
    handle http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:61
    onsuccess http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:22
    b http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:55
    c http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    fireWith http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    l http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:²
    o http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    send http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    ajax http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    send http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:54
    poll http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:43
    b http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:56
    c http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    fireWith http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    l http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    o http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    send http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    ajax http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml line 2 > injectedScript:2
    send http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:54
    offer http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:43
    handle http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:44
    ab http://127.0.0.1:8082/xxxxxxxxxxxxx/javax.faces.resource/core.js.xhtml?ln=primefaces&v=12.0.0&e=12.0.0:37
    onclick http://127.0.0.1:8082/xxxxxxxxxxxxx/xxxxxxxxxxxxx.xhtml:1
xxxxxxxxxxxxx.xhtml line 2 > injectedScript:177:326
